version: "3.8"

services:
  flutter-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./assets:/usr/share/nginx/html/assets
    networks:
      - flutter-network

networks:
  flutter-network:
    driver: bridge
