version: "3.8"

services:
  flutter-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    restart: always
    networks:
      - flutter-network

networks:
  flutter-network:
    driver: bridge
