version: "3.8"

services:
  flutter-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - .:/app
    networks:
      - flutter-network
    environment:
      - FLUTTER_WEB_HOSTNAME=0.0.0.0
      - FLUTTER_WEB_PORT=8080
    stdin_open: true
    tty: true

networks:
  flutter-network:
    driver: bridge
