name: flutter_starter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  validators: ^3.0.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.5.1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/default_background.jpg
