name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.4

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Clean project
        run: flutter clean

      - name: Build Flutter web app
        run: flutter build web --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: flutter-web-build
          path: build/web

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flutter-starter:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/flutter-starter:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            cd github/dart-flutter-starter
            git fetch origin
            git reset --hard origin/main
            docker pull ${{ secrets.DOCKER_USERNAME }}/flutter-starter:latest
            docker-compose down
            docker-compose rm -f
            docker rmi ${{ secrets.DOCKER_USERNAME }}/flutter-starter:latest || true
            docker-compose up --force-recreate --build -d
